version: '3.7'

networks:
  load-balancer-nginx:
    name: load-balancer-ngnix
    external: true

services:
  ngimx:
    build:
      context: ./docker
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - 80:80
    networks:
      - load-balancer-nginx
    