version: '3.7'

networks:
  load-balancer-nginx:
    name: load-balancer-ngnix
    external: true

services:
  app:
    build:
      context: .
      dockerfile: ./docker/DockerFile
    ports:
      - "6000"
    networks:
      - load-balancer-nginx
    volumes:
      - ./src:/src/

  nginx:
    image: nginx:latest
    depends_on:
      - app
    volumes:
      - ./ngnix.conf:/etc/nginx/nginx.confg:ro
    ports:
      - 80:80
    networks:
      - load-balancer-nginx
    